/*
 * SPDX-FileCopyrightText: 2026 Stoian Alexandru
 * SPDX-License-Identifier: MIT
 */
/**
 * @file test_sw_gcm.c
 * @brief Unit tests for the software AES-256-GCM fallback (swgcm).
 *
 * Reference vectors in `test_sw_gcm_vectors.h` are generated by
 * `tools/gen_sw_gcm_vectors.py` (Python `cryptography` / OpenSSL), so they
 * cannot drift by hand-transcription. Covers the AES-256 block KAT, the
 * empty / 16-zero / 64-zero / 56-byte GCM vectors (whole-buffer and
 * 1-byte-stepped streaming), tamper rejection, and a software-vs-hardware
 * mbedTLS cross-check in both directions.
 */

#include "unity.h"
#include "sw_gcm.h"
#include "test_sw_gcm_vectors.h"

#include "mbedtls/gcm.h"

#include <string.h>

/* From sw_aes.c (encrypt direction only; kept out of the public header). */
void sw_aes256_expand_key(const uint8_t key[32], uint32_t rk[60]);
void sw_aes256_encrypt_block(const uint32_t rk[60], const uint8_t in[16], uint8_t out[16]);

void test_sw_aes256_block_kat(void)
{
    uint8_t ct[16];
    uint32_t rk[60];

    sw_aes256_expand_key(V_AES_KEY, rk);
    sw_aes256_encrypt_block(rk, V_AES_PT, ct);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(V_AES_CT, ct, 16);
    memset(rk, 0, sizeof(rk));
}

/** Drive one full streaming session with @p step-byte updates. */
static void sw_gcm_oneshot_stepped(bool encrypt, const uint8_t *key, const uint8_t *nonce,
                                   const uint8_t *in, size_t len, size_t step,
                                   uint8_t *out, uint8_t *tag)
{
    sw_gcm_ctx_t ctx;
    size_t off = 0;

    sw_gcm_init(&ctx);
    TEST_ASSERT_EQUAL_INT(0, sw_gcm_setkey(&ctx, key));
    TEST_ASSERT_EQUAL_INT(0, sw_gcm_starts(&ctx, encrypt, nonce));
    while (off < len) {
        size_t n = (len - off < step) ? len - off : step;
        size_t olen = 0;
        TEST_ASSERT_EQUAL_INT(0, sw_gcm_update(&ctx, in + off, n, out + off, &olen));
        TEST_ASSERT_EQUAL_UINT(n, olen);
        off += n;
    }
    {
        uint8_t tail[16];
        size_t tail_len = 0;
        TEST_ASSERT_EQUAL_INT(0, sw_gcm_finish(&ctx, tail, &tail_len, tag));
        TEST_ASSERT_EQUAL_UINT(0, tail_len);
    }
    sw_gcm_free(&ctx);
}

static void sw_gcm_check_vector(size_t len, const uint8_t *key, const uint8_t *nonce,
                                const uint8_t *pt, const uint8_t *want_ct,
                                const uint8_t *want_tag)
{
    uint8_t ct[64];
    uint8_t tag[16];
    uint8_t back[64];
    uint8_t tag2[16];

    TEST_ASSERT_TRUE(len <= sizeof(ct));
    /* Whole buffer, 1-byte streaming, and a mid-size step must all agree. */
    sw_gcm_oneshot_stepped(true, key, nonce, pt, len, len, ct, tag);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(want_ct, ct, len);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(want_tag, tag, 16);
    sw_gcm_oneshot_stepped(true, key, nonce, pt, len, 1, ct, tag);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(want_ct, ct, len);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(want_tag, tag, 16);
    sw_gcm_oneshot_stepped(true, key, nonce, pt, len, 7, ct, tag);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(want_ct, ct, len);
    /* Decrypt round-trips and authenticates. */
    sw_gcm_oneshot_stepped(false, key, nonce, want_ct, len, 5, back, tag2);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(pt, back, len);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(want_tag, tag2, 16);
    /* Tampering the ciphertext changes the tag. */
    memcpy(back, want_ct, len);
    back[0] ^= 0x01;
    sw_gcm_oneshot_stepped(false, key, nonce, back, len, 64, back, tag2);
    TEST_ASSERT_TRUE(memcmp(tag2, want_tag, 16) != 0);
}

void test_sw_gcm_empty_vector(void)
{
    static const uint8_t key[32] = { 0 };
    static const uint8_t nonce[12] = { 0 };
    uint8_t tag[16];

    sw_gcm_oneshot_stepped(true, key, nonce, NULL, 0, 1, NULL, tag);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(V_EMPTY_TAG, tag, 16);
}

void test_sw_gcm_16zero_vector(void)
{
    static const uint8_t key[32] = { 0 };
    static const uint8_t nonce[12] = { 0 };
    static const uint8_t pt[16] = { 0 };

    sw_gcm_check_vector(16, key, nonce, pt, V_16Z_CT, V_16Z_TAG);
}

void test_sw_gcm_64zero_vector(void)
{
    static const uint8_t key[32] = { 0 };
    static const uint8_t nonce[12] = { 0 };
    static const uint8_t pt[64] = { 0 };

    sw_gcm_check_vector(64, key, nonce, pt, V_64Z_CT, V_64Z_TAG);
}

void test_sw_gcm_ref3_vector(void)
{
    sw_gcm_check_vector(sizeof(V_REF3_PT), V_REF3_KEY, V_REF3_NONCE,
                        V_REF3_PT, V_REF3_CT, V_REF3_TAG);
}

void test_sw_gcm_hw_crosscheck(void)
{
    /* Both engines must produce byte-identical output for an odd length
     * (multi-block + partial tail), in both directions. */
    uint8_t key[32];
    uint8_t nonce[12];
    static const uint8_t pt[1000] = { [0] = 0x41, [999] = 0x5a };
    uint8_t sw_ct[sizeof(pt)];
    uint8_t hw_ct[sizeof(pt)];
    uint8_t sw_tag[16];
    uint8_t hw_tag[16];
    uint8_t back[sizeof(pt)];
    int i;

    for (i = 0; i < 32; i++) {
        key[i] = (uint8_t)(i * 3 + 1);
    }
    for (i = 0; i < 12; i++) {
        nonce[i] = (uint8_t)(i * 5 + 2);
    }
    sw_gcm_oneshot_stepped(true, key, nonce, pt, sizeof(pt), 13, sw_ct, sw_tag);
    {
        mbedtls_gcm_context hctx;
        uint8_t tail[16];
        size_t olen = 0;
        size_t tail_len = 0;
        mbedtls_gcm_init(&hctx);
        TEST_ASSERT_EQUAL_INT(0, mbedtls_gcm_setkey(&hctx, MBEDTLS_CIPHER_ID_AES, key, 256));
        TEST_ASSERT_EQUAL_INT(0, mbedtls_gcm_starts(&hctx, MBEDTLS_GCM_ENCRYPT, nonce, 12));
        TEST_ASSERT_EQUAL_INT(0, mbedtls_gcm_update(&hctx, pt, sizeof(pt), hw_ct, sizeof(hw_ct), &olen));
        TEST_ASSERT_EQUAL_INT(0, mbedtls_gcm_finish(&hctx, tail, 16, &tail_len, hw_tag, 16));
        mbedtls_gcm_free(&hctx);
        /* mbedTLS buffers up to 15 trailing bytes internally. */
        memcpy(hw_ct + olen, tail, tail_len);
        TEST_ASSERT_EQUAL_UINT(sizeof(pt), olen + tail_len);
    }
    TEST_ASSERT_EQUAL_UINT8_ARRAY(sw_ct, hw_ct, sizeof(pt));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(sw_tag, hw_tag, 16);
    /* Software decrypts the hardware output. */
    sw_gcm_oneshot_stepped(false, key, nonce, hw_ct, sizeof(hw_ct), 511, back, sw_tag);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(pt, back, sizeof(pt));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(hw_tag, sw_tag, 16);
}
