/*
 * SPDX-FileCopyrightText: 2026 Stoian Alexandru
 * SPDX-License-Identifier: MIT
 *
 * Generated by tools/gen_tui_font.py - do not edit by hand.
 */
#ifndef P4MINISHELL_TUI_FONTS_H
#define P4MINISHELL_TUI_FONTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/** One candidate TUI cell: the font plus its logical cell size. */
typedef struct {
    int cell_w;
    int cell_h;
    const lv_font_t *font;
} tui_font_cell_t;

extern const tui_font_cell_t tui_font_cells[];

extern const int tui_font_cell_count;

#ifdef __cplusplus
}
#endif

#endif /* P4MINISHELL_TUI_FONTS_H */
