#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Stoian Alexandru
# SPDX-License-Identifier: MIT
"""gen_gfx_font.py - generate components/gfx/gfx_font.c (8x8 ASCII font).

Renders printable ASCII (0x20..0x7E) from the public-domain unscii-8 TTF
bundled with LVGL into an 8x8 1-bit table for the pure `gfx_surface_text`
rasterizer. The generated C file is committed; re-run only if the font or
cell size changes.

Usage: python tools/gen_gfx_font.py
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF = os.path.join(ROOT, "managed_components", "lvgl__lvgl", "scripts",
                   "built_in_font", "unscii-8.ttf")
OUT = os.path.join(ROOT, "components", "gfx", "gfx_font.c")

FIRST = 0x20
LAST = 0x7E
W = 8
H = 8


def render(font):
    glyphs = []
    blanks = []
    for code in range(FIRST, LAST + 1):
        im = Image.new("L", (W, H), 0)
        ImageDraw.Draw(im).text((0, 0), chr(code), fill=255, font=font)
        rows = []
        for y in range(H):
            bits = 0
            for x in range(W):
                if im.getpixel((x, y)) > 127:
                    bits |= 1 << (7 - x)
            rows.append(bits)
        if code != FIRST and all(b == 0 for b in rows):
            blanks.append(code)
        glyphs.append((code, rows))
    return glyphs, blanks


def emit(glyphs):
    lines = [
        "/**",
        " * @file gfx_font.c",
        " * @brief Generated 8x8 ASCII glyph table for `gfx_surface_text`.",
        " *",
        " * Generated by tools/gen_gfx_font.py from the public-domain unscii-8",
        " * TTF (bundled with LVGL scripts/built_in_font). Do not edit by hand.",
        " * Rows are MSB-first (bit 7 = leftmost pixel), one byte per row.",
        " */",
        "",
        '#include "gfx.h"',
        "",
        "const uint8_t gfx_font8x8[GFX_FONT_GLYPHS][GFX_FONT_H] = {",
    ]
    for code, rows in glyphs:
        ch = chr(code)
        label = "space" if ch == " " else ch
        body = ", ".join("0x%02X" % b for b in rows)
        lines.append("    { %s }, /* 0x%02X '%s' */" % (body, code, label))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    if not os.path.exists(TTF):
        print("FAIL: font not found: %s" % TTF)
        return 1
    font = ImageFont.truetype(TTF, H)
    glyphs, blanks = render(font)
    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(emit(glyphs))
    print("WROTE %s (%d glyphs, %d bytes)" % (OUT, len(glyphs),
                                              os.path.getsize(OUT)))
    if blanks:
        print("WARN blank glyphs: %s" % " ".join("0x%02X" % c for c in blanks))
    else:
        print("OK no unexpected blank glyphs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
