#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Stoian Alexandru
# SPDX-License-Identifier: MIT
"""Generate test/main/test_sw_gcm_vectors.h for the software AES-GCM tests.

Uses Python `cryptography` (OpenSSL) as an independent reference so the
firmware's AES-256-GCM fallback is checked against real-world output, not
hand-transcribed constants:

    python tools/gen_sw_gcm_vectors.py

Vectors: AES-256 block KAT, GCM empty / 16-zero / 64-zero, and a 56-byte
text with key 00..1f and nonce 00..0b. Re-run after any intentional format
change (never to make a failing test pass).
"""

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

OUT = "test/main/test_sw_gcm_vectors.h"


def cbytes(name, data):
    return "static const uint8_t %s[%d] = { %s };" % (
        name, len(data), ", ".join("0x%02x" % b for b in data))


def main():
    key0 = bytes(32)
    nonce0 = bytes(12)
    key3 = bytes(range(32))
    nonce3 = bytes(range(12))
    pt3 = b"The quick brown fox jumps over the lazy dog, 1234567890!"

    lines = []
    enc = Cipher(algorithms.AES(bytes(range(32))), modes.ECB()).encryptor()
    lines.append(cbytes("V_AES_KEY", bytes(range(32))))
    lines.append(cbytes("V_AES_PT", bytes(range(16))))
    lines.append(cbytes("V_AES_CT", enc.update(bytes(range(16))) + enc.finalize()))

    lines.append(cbytes("V_EMPTY_TAG", AESGCM(key0).encrypt(nonce0, b"", None)))

    c16 = AESGCM(key0).encrypt(nonce0, bytes(16), None)
    lines.append(cbytes("V_16Z_CT", c16[:16]))
    lines.append(cbytes("V_16Z_TAG", c16[16:]))

    c64 = AESGCM(key0).encrypt(nonce0, bytes(64), None)
    lines.append(cbytes("V_64Z_CT", c64[:64]))
    lines.append(cbytes("V_64Z_TAG", c64[64:]))

    c3 = AESGCM(key3).encrypt(nonce3, pt3, None)
    lines.append(cbytes("V_REF3_KEY", key3))
    lines.append(cbytes("V_REF3_NONCE", nonce3))
    lines.append(cbytes("V_REF3_PT", pt3))
    lines.append(cbytes("V_REF3_CT", c3[:-16]))
    lines.append(cbytes("V_REF3_TAG", c3[-16:]))

    header = [
        "/*",
        " * SPDX-FileCopyrightText: 2026 Stoian Alexandru",
        " * SPDX-License-Identifier: MIT",
        " */",
        "/** Generated by tools/gen_sw_gcm_vectors.py (OpenSSL). Do not hand-edit. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header + lines) + "\n")
    print("wrote %s (%d vectors)" % (OUT, len(lines)))


if __name__ == "__main__":
    main()
